import 'dart:io';
import 'colors.dart';
import 'generators/flavors_generator.dart';
import 'generators/fastlane_generator.dart';
import 'generators/github_actions_generator.dart';
import 'generators/firebase_generator.dart';

class FlutterCiCdWizard {
  final _config = <String, dynamic>{};

  Future<void> run(List<String> args) async {
    _printBanner();

    if (args.contains('--help') || args.contains('-h')) {
      _printHelp();
      return;
    }

    if (args.contains('--version') || args.contains('-v')) {
      print('flutter_cicd_wizard version 1.0.0');
      return;
    }

    print('${Clr.cyan}Welcome! Let\'s set up your Flutter project with CI/CD + Flavors.\n${Clr.reset}');

    await _collectProjectInfo();
    await _selectFeatures();
    await _generateFiles();

    _printSuccess();
  }

  // ─── Banner ───────────────────────────────────────────────────────────────

  void _printBanner() {
    print('''
${Clr.purple}
╔══════════════════════════════════════════════════════════╗
║                                                          ║
║        🚀  Flutter CI/CD + Flavors Wizard  🚀            ║
║                                                          ║
║   Instantly scaffold CI/CD pipelines & app flavors       ║
║   for your Flutter project — by Hossam Aboud             ║
║                                                          ║
╚══════════════════════════════════════════════════════════╝
${Clr.reset}''');
  }

  void _printHelp() {
    print('''
${Clr.cyan}Usage:${Clr.reset}
  flutter_cicd_wizard            Run the interactive wizard
  flutter_cicd_wizard --help     Show this help
  flutter_cicd_wizard --version  Show version

${Clr.cyan}What it generates:${Clr.reset}
  • Flutter Flavors (dev / staging / prod)
  • Fastlane setup (iOS + Android)
  • GitHub Actions workflows
  • Firebase App Distribution integration
  • Environment config files (.env per flavor)
''');
  }

  // ─── Data collection ──────────────────────────────────────────────────────

  Future<void> _collectProjectInfo() async {
    print('${Clr.bold}── Project Info ─────────────────────────────────────${Clr.reset}\n');

    _config['appName']     = await _ask('App name', defaultVal: 'MyApp');
    _config['packageName'] = await _ask('Package name (e.g. com.company.app)', defaultVal: 'com.example.myapp');
    _config['outputDir']   = await _ask('Output directory', defaultVal: '.');

    print('');
  }

  Future<void> _selectFeatures() async {
    print('${Clr.bold}── Select Features ──────────────────────────────────${Clr.reset}\n');

    _config['flavors']         = await _confirm('Generate Flutter Flavors (dev/staging/prod)?');
    _config['fastlane']        = await _confirm('Generate Fastlane setup?');
    _config['githubActions']   = await _confirm('Generate GitHub Actions workflows?');
    _config['firebase']        = await _confirm('Add Firebase App Distribution?');
    _config['envFiles']        = await _confirm('Generate .env files per flavor?');

    if (_config['fastlane'] == true) {
      _config['platform'] = await _choose(
        'Which platforms for Fastlane?',
        ['both', 'android', 'ios'],
      );
    }

    print('');
  }

  // ─── Generation ───────────────────────────────────────────────────────────

  Future<void> _generateFiles() async {
    final outDir = _config['outputDir'] as String;

    print('${Clr.bold}── Generating Files ─────────────────────────────────${Clr.reset}\n');

    if (_config['flavors'] == true) {
      await FlavorsGenerator(_config).generate(outDir);
      _done('Flutter Flavors');
    }

    if (_config['fastlane'] == true) {
      await FastlaneGenerator(_config).generate(outDir);
      _done('Fastlane');
    }

    if (_config['githubActions'] == true) {
      await GithubActionsGenerator(_config).generate(outDir);
      _done('GitHub Actions');
    }

    if (_config['firebase'] == true) {
      await FirebaseGenerator(_config).generate(outDir);
      _done('Firebase App Distribution');
    }

    if (_config['envFiles'] == true) {
      await _generateEnvFiles(outDir);
      _done('.env files');
    }
  }

  Future<void> _generateEnvFiles(String outDir) async {
    for (final flavor in ['dev', 'staging', 'prod']) {
      final file = File('$outDir/.env.$flavor');
      await file.writeAsString(_envContent(flavor));
    }
  }

  String _envContent(String flavor) {
    final appName = _config['appName'];
    return '''# $flavor environment — generated by flutter_cicd_wizard
FLAVOR=$flavor
APP_NAME=$appName ${flavor == 'prod' ? '' : '(${flavor[0].toUpperCase()}${flavor.substring(1)})'}
API_BASE_URL=${flavor == 'prod' ? 'https://api.yourapp.com' : flavor == 'staging' ? 'https://staging-api.yourapp.com' : 'https://dev-api.yourapp.com'}
ENABLE_LOGS=${flavor == 'prod' ? 'false' : 'true'}
ENABLE_CRASHLYTICS=${flavor == 'prod' ? 'true' : 'false'}
''';
  }

  // ─── Success message ──────────────────────────────────────────────────────

  void _printSuccess() {
    final outDir = _config['outputDir'];
    print('''
${Clr.green}
╔══════════════════════════════════════════════════════════╗
║                                                          ║
║   ✅  All files generated successfully!                  ║
║                                                          ║
╚══════════════════════════════════════════════════════════╝
${Clr.reset}
${Clr.cyan}Next steps:${Clr.reset}

  1. Copy generated files into your Flutter project root
  2. Add secrets to GitHub → Settings → Secrets:
       PLAY_STORE_JSON_KEY    (Android)
       APP_STORE_CONNECT_KEY  (iOS)
       FIREBASE_TOKEN         (Firebase)
  3. Commit & push — your pipeline is ready! 🚀

${Clr.cyan}Output location:${Clr.reset} $outDir
${Clr.muted}Built with ❤️  by Hossam Aboud — github.com/hossam-aboud${Clr.reset}
''');
  }

  // ─── Helpers ──────────────────────────────────────────────────────────────

  Future<String> _ask(String question, {String defaultVal = ''}) async {
    stdout.write('${Clr.yellow}?${Clr.reset} $question');
    if (defaultVal.isNotEmpty) stdout.write(' ${Clr.muted}[$defaultVal]${Clr.reset}');
    stdout.write(': ');
    final input = stdin.readLineSync()?.trim() ?? '';
    return input.isEmpty ? defaultVal : input;
  }

  Future<bool> _confirm(String question) async {
    stdout.write('${Clr.yellow}?${Clr.reset} $question ${Clr.muted}(Y/n)${Clr.reset}: ');
    final input = stdin.readLineSync()?.trim().toLowerCase() ?? '';
    return input.isEmpty || input == 'y' || input == 'yes';
  }

  Future<String> _choose(String question, List<String> options) async {
    print('${Clr.yellow}?${Clr.reset} $question');
    for (var i = 0; i < options.length; i++) {
      print('  ${Clr.cyan}${i + 1})${Clr.reset} ${options[i]}');
    }
    stdout.write('  Choose [1]: ');
    final input = stdin.readLineSync()?.trim() ?? '';
    final idx   = int.tryParse(input);
    if (idx != null && idx >= 1 && idx <= options.length) return options[idx - 1];
    return options[0];
  }

  void _done(String label) {
    print('  ${Clr.green}✔${Clr.reset}  $label generated');
  }
}
