import 'dart:io';

class FastlaneGenerator {
  final Map<String, dynamic> config;
  FastlaneGenerator(this.config);

  Future<void> generate(String outDir) async {
    final platform = config['platform'] as String? ?? 'both';
    final package  = config['packageName'] as String;
    final appName  = config['appName'] as String;

    final dir = Directory('$outDir/fastlane');
    await dir.create(recursive: true);

    // Gemfile
    await File('$outDir/Gemfile').writeAsString(_gemfile());

    if (platform == 'android' || platform == 'both') {
      await _generateAndroid(dir, package, appName);
    }
    if (platform == 'ios' || platform == 'both') {
      await _generateIos(dir, package, appName);
    }

    // Shared Appfile
    await File('${dir.path}/Appfile').writeAsString(_appfile(package));

    // .env.secret template
    await File('$outDir/.env.secret.template').writeAsString(_secretsTemplate());
  }

  Future<void> _generateAndroid(Directory dir, String package, String appName) async {
    final androidDir = Directory('${dir.path}/android');
    await androidDir.create(recursive: true);

    await File('${androidDir.path}/Fastfile').writeAsString(_androidFastfile(package));
  }

  Future<void> _generateIos(Directory dir, String package, String appName) async {
    final iosDir = Directory('${dir.path}/ios');
    await iosDir.create(recursive: true);

    await File('${iosDir.path}/Fastfile').writeAsString(_iosFastfile(appName));
  }

  String _gemfile() => '''
source "https://rubygems.org"

gem "fastlane"
gem "firebase_app_distribution"  # remove if not using Firebase
''';

  String _appfile(String package) => '''
# Generated by flutter_cicd_wizard
app_identifier("$package")
''';

  String _androidFastfile(String package) => '''
# Generated by flutter_cicd_wizard — Android Fastfile

default_platform(:android)

platform :android do

  # ── Build ────────────────────────────────────────────────────────────────

  desc "Build APK for a given flavor"
  lane :build do |options|
    flavor = options[:flavor] || "dev"
    sh("flutter build apk --flavor #{flavor} -t lib/main_#{flavor}.dart --release")
  end

  desc "Build AAB for Play Store"
  lane :build_aab do |options|
    flavor = options[:flavor] || "prod"
    sh("flutter build appbundle --flavor #{flavor} -t lib/main_#{flavor}.dart --release")
  end

  # ── Deploy ───────────────────────────────────────────────────────────────

  desc "Upload APK to Firebase App Distribution (dev/staging)"
  lane :distribute_firebase do |options|
    flavor  = options[:flavor] || "dev"
    apk_path = "../build/app/outputs/flutter-apk/app-#{flavor}-release.apk"

    build(flavor: flavor)

    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID_ANDROID_#{flavor.upcase}"],
      apk_path: apk_path,
      groups: "testers",
      release_notes: "Flavor: #{flavor} — built by Fastlane"
    )
  end

  desc "Upload AAB to Google Play (prod)"
  lane :deploy_play_store do
    build_aab(flavor: "prod")

    upload_to_play_store(
      track: "internal",
      aab: "../build/app/outputs/bundle/prodRelease/app-prod-release.aab",
      json_key_data: ENV["PLAY_STORE_JSON_KEY"],
      package_name: "$package"
    )
  end

  # ── Version bump ─────────────────────────────────────────────────────────

  desc "Bump version code in pubspec.yaml"
  lane :bump_version do
    path = "../pubspec.yaml"
    content = File.read(path)
    current = content.match(/version: (\\d+\\.\\d+\\.\\d+)\\+(\\d+)/)[2].to_i
    new_content = content.sub(/\\+(\\d+)/, "+#{current + 1}")
    File.write(path, new_content)
    UI.success("Version code bumped to #{current + 1}")
  end

end
''';

  String _iosFastfile(String appName) => '''
# Generated by flutter_cicd_wizard — iOS Fastfile

default_platform(:ios)

platform :ios do

  # ── Certificates ─────────────────────────────────────────────────────────

  desc "Sync signing certificates with match"
  lane :sync_certs do |options|
    type = options[:type] || "development"
    match(
      type: type,
      readonly: is_ci,
      git_url: ENV["MATCH_GIT_URL"],
      git_basic_authorization: ENV["MATCH_GIT_TOKEN"]
    )
  end

  # ── Build ────────────────────────────────────────────────────────────────

  desc "Build IPA for a given flavor"
  lane :build do |options|
    flavor = options[:flavor] || "dev"
    sync_certs(type: flavor == "prod" ? "appstore" : "development")
    sh("flutter build ios --flavor #{flavor} -t lib/main_#{flavor}.dart --release --no-codesign")
    build_ios_app(
      workspace: "ios/Runner.xcworkspace",
      scheme: "$appName-#{flavor}",
      export_method: flavor == "prod" ? "app-store" : "development"
    )
  end

  # ── Deploy ───────────────────────────────────────────────────────────────

  desc "Upload to Firebase App Distribution (dev/staging)"
  lane :distribute_firebase do |options|
    flavor = options[:flavor] || "dev"
    build(flavor: flavor)
    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID_IOS_#{flavor.upcase}"],
      groups: "testers",
      release_notes: "Flavor: #{flavor} — built by Fastlane"
    )
  end

  desc "Upload to TestFlight (prod)"
  lane :deploy_testflight do
    build(flavor: "prod")
    upload_to_testflight(
      api_key_path: ENV["APP_STORE_CONNECT_KEY_PATH"],
      skip_waiting_for_build_processing: true
    )
  end

end
''';

  String _secretsTemplate() => '''
# ── .env.secret.template — generated by flutter_cicd_wizard ─────────────────
# Copy to .env.secret and fill in your values
# NEVER commit .env.secret to git!

# Android
PLAY_STORE_JSON_KEY=<base64 encoded service account JSON>

# iOS
APP_STORE_CONNECT_KEY_PATH=./AuthKey.p8
MATCH_GIT_URL=https://github.com/your-org/certificates
MATCH_GIT_TOKEN=<github_personal_access_token>

# Firebase App Distribution
FIREBASE_TOKEN=<firebase_ci_token>
FIREBASE_APP_ID_ANDROID_DEV=1:xxxx:android:yyyy
FIREBASE_APP_ID_ANDROID_STAGING=1:xxxx:android:yyyy
FIREBASE_APP_ID_ANDROID_PROD=1:xxxx:android:yyyy
FIREBASE_APP_ID_IOS_DEV=1:xxxx:ios:yyyy
FIREBASE_APP_ID_IOS_STAGING=1:xxxx:ios:yyyy
FIREBASE_APP_ID_IOS_PROD=1:xxxx:ios:yyyy
''';
}
