import 'dart:io';

class FirebaseGenerator {
  final Map<String, dynamic> config;
  FirebaseGenerator(this.config);

  Future<void> generate(String outDir) async {
    final dir = Directory('$outDir/firebase');
    await dir.create(recursive: true);

    await File('${dir.path}/firebase_setup.md').writeAsString(_setupGuide());
    await File('${dir.path}/firebase_options_template.dart').writeAsString(_optionsTemplate());
  }

  String _setupGuide() => '''
# Firebase App Distribution Setup
# Generated by flutter_cicd_wizard

## Step 1 — Create Firebase projects

Create 3 Firebase projects (one per flavor):
- ${config['appName']}-dev
- ${config['appName']}-staging
- ${config['appName']}-prod

## Step 2 — Register apps

For each project register:
- Android app: `${config['packageName']}.dev` / `.staging` / (none for prod)
- iOS app: same bundle IDs

Download the `google-services.json` and `GoogleService-Info.plist` files
and place them in the correct flavor folders:

```
android/app/src/dev/google-services.json
android/app/src/staging/google-services.json
android/app/src/prod/google-services.json

ios/config/dev/GoogleService-Info.plist
ios/config/staging/GoogleService-Info.plist
ios/config/prod/GoogleService-Info.plist
```

## Step 3 — Enable App Distribution

In each Firebase project:
Firebase Console → App Distribution → Get Started → Create tester groups

Recommended groups:
- `testers` (dev + staging)
- `stakeholders` (staging only)

## Step 4 — Get Firebase CI token

```bash
firebase login:ci
```

Copy the token → add to GitHub Secrets as `FIREBASE_TOKEN`

## Step 5 — Get App IDs

Firebase Console → Project Settings → Your apps → App ID

Add to GitHub Secrets:
- FIREBASE_APP_ID_ANDROID_DEV
- FIREBASE_APP_ID_ANDROID_STAGING  
- FIREBASE_APP_ID_ANDROID_PROD
- FIREBASE_APP_ID_IOS_DEV
- FIREBASE_APP_ID_IOS_STAGING
- FIREBASE_APP_ID_IOS_PROD

## Step 6 — Add FlutterFire to pubspec.yaml

```yaml
dependencies:
  firebase_core: ^2.x.x
  firebase_crashlytics: ^3.x.x   # optional
  firebase_analytics: ^10.x.x    # optional
```

Then run:
```bash
flutterfire configure
```
''';

  String _optionsTemplate() => '''
// firebase_options_template.dart — generated by flutter_cicd_wizard
// Use flutterfire configure to auto-generate the real file per flavor

// Run this for each flavor:
// flutterfire configure --project=your-project-dev   --out=lib/firebase_options_dev.dart
// flutterfire configure --project=your-project-staging --out=lib/firebase_options_staging.dart
// flutterfire configure --project=your-project-prod  --out=lib/firebase_options_prod.dart

// Then in each main_<flavor>.dart:
// await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
''';
}
