import 'dart:io';

class FlavorsGenerator {
  final Map<String, dynamic> config;
  FlavorsGenerator(this.config);

  Future<void> generate(String outDir) async {
    final appName    = config['appName'] as String;
    final package    = config['packageName'] as String;

    final dir = Directory('$outDir/flavors');
    await dir.create(recursive: true);

    // main_dev.dart
    await File('${dir.path}/main_dev.dart').writeAsString(_mainFlavor(
      flavor: 'dev',
      appName: '$appName (Dev)',
      package: package,
    ));

    // main_staging.dart
    await File('${dir.path}/main_staging.dart').writeAsString(_mainFlavor(
      flavor: 'staging',
      appName: '$appName (Staging)',
      package: package,
    ));

    // main_prod.dart
    await File('${dir.path}/main_prod.dart').writeAsString(_mainFlavor(
      flavor: 'prod',
      appName: appName,
      package: package,
    ));

    // app_flavor.dart
    await File('${dir.path}/app_flavor.dart').writeAsString(_appFlavorEnum());

    // flavor_config.dart
    await File('${dir.path}/flavor_config.dart').writeAsString(_flavorConfig(appName));

    // android/build.gradle snippet
    final androidDir = Directory('$outDir/flavors/android');
    await androidDir.create(recursive: true);
    await File('${androidDir.path}/build_gradle_flavors.gradle').writeAsString(_androidGradle(appName, package));

    // iOS Xcode schemes info
    await File('${androidDir.path}/../ios_schemes_readme.md').writeAsString(_iosSchemes(appName));
  }

  String _mainFlavor({required String flavor, required String appName, required String package}) => '''
import 'package:flutter/material.dart';
import 'app_flavor.dart';
import 'flavor_config.dart';
// ignore: uri_does_not_exist
import 'package:${package.replaceAll('.', '_')}/app.dart';

void main() {
  FlavorConfig.instance = FlavorConfig(
    flavor: AppFlavor.${flavor},
    name: '$appName',
    apiBaseUrl: ${_apiUrl(flavor)},
    enableLogs: ${flavor != 'prod'},
    enableCrashlytics: ${flavor == 'prod'},
  );

  runApp(const App());
}
''';

  String _apiUrl(String flavor) {
    if (flavor == 'prod') return "'https://api.yourapp.com'";
    if (flavor == 'staging') return "'https://staging-api.yourapp.com'";
    return "'https://dev-api.yourapp.com'";
  }

  String _appFlavorEnum() => '''
enum AppFlavor { dev, staging, prod }

extension AppFlavorX on AppFlavor {
  String get name {
    switch (this) {
      case AppFlavor.dev:     return 'dev';
      case AppFlavor.staging: return 'staging';
      case AppFlavor.prod:    return 'prod';
    }
  }

  bool get isDev     => this == AppFlavor.dev;
  bool get isStaging => this == AppFlavor.staging;
  bool get isProd    => this == AppFlavor.prod;
}
''';

  String _flavorConfig(String appName) => '''
import 'app_flavor.dart';

class FlavorConfig {
  final AppFlavor flavor;
  final String name;
  final String apiBaseUrl;
  final bool enableLogs;
  final bool enableCrashlytics;

  FlavorConfig({
    required this.flavor,
    required this.name,
    required this.apiBaseUrl,
    required this.enableLogs,
    required this.enableCrashlytics,
  });

  static late FlavorConfig instance;

  static bool get isDev     => instance.flavor.isDev;
  static bool get isStaging => instance.flavor.isStaging;
  static bool get isProd    => instance.flavor.isProd;
}
''';

  String _androidGradle(String appName, String package) => '''
// ─── Add this inside android { } in your app/build.gradle ───────────────────
// Generated by flutter_cicd_wizard

flavorDimensions "environment"

productFlavors {
    dev {
        dimension "environment"
        applicationIdSuffix ".dev"
        versionNameSuffix "-dev"
        resValue "string", "app_name", "$appName Dev"
    }
    staging {
        dimension "environment"
        applicationIdSuffix ".staging"
        versionNameSuffix "-staging"
        resValue "string", "app_name", "$appName Staging"
    }
    prod {
        dimension "environment"
        resValue "string", "app_name", "$appName"
    }
}
// ────────────────────────────────────────────────────────────────────────────
''';

  String _iosSchemes(String appName) => '''
# iOS Schemes Setup — generated by flutter_cicd_wizard

## Steps to add flavors in Xcode:

1. Open `ios/Runner.xcworkspace` in Xcode
2. Go to **Product → Scheme → Manage Schemes**
3. Duplicate the existing `Runner` scheme 3 times and rename:
   - `$appName-dev`
   - `$appName-staging`
   - `$appName-prod`

4. For each scheme, edit **Run → Build Configuration**:
   - dev     → Debug-dev / Release-dev
   - staging → Debug-staging / Release-staging
   - prod    → Debug-prod / Release-prod

5. In `ios/Runner/Info.plist` set:
```xml
<key>CFBundleName</key>
<string>\$(APP_NAME)</string>
```

6. Add `APP_NAME` to each `.xcconfig` file:
   - `Debug-dev.xcconfig`:     `APP_NAME = $appName Dev`
   - `Debug-staging.xcconfig`: `APP_NAME = $appName Staging`
   - `Debug-prod.xcconfig`:    `APP_NAME = $appName`

## Run on device:
```bash
flutter run --flavor dev -t lib/main_dev.dart
flutter run --flavor staging -t lib/main_staging.dart
flutter run --flavor prod -t lib/main_prod.dart
```
''';
}
