import 'dart:io';

class GithubActionsGenerator {
  final Map<String, dynamic> config;
  GithubActionsGenerator(this.config);

  Future<void> generate(String outDir) async {
    final dir = Directory('$outDir/.github/workflows');
    await dir.create(recursive: true);

    // 1. PR checks
    await File('${dir.path}/pr_checks.yml').writeAsString(_prChecks());

    // 2. Deploy dev (on push to develop)
    await File('${dir.path}/deploy_dev.yml').writeAsString(_deployFlavor('dev', 'develop'));

    // 3. Deploy staging (on push to staging)
    await File('${dir.path}/deploy_staging.yml').writeAsString(_deployFlavor('staging', 'staging'));

    // 4. Deploy prod (on push to main / tag)
    await File('${dir.path}/deploy_prod.yml').writeAsString(_deployProd());

    // 5. Codemagic alternative readme
    await File('$outDir/CODEMAGIC_ALTERNATIVE.md').writeAsString(_codemagicNote());
  }

  String _prChecks() => '''
# Generated by flutter_cicd_wizard
# Runs on every Pull Request — analyze + test + build check

name: PR Checks

on:
  pull_request:
    branches: [ main, develop, staging ]

jobs:
  analyze_and_test:
    name: Analyze & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test --coverage

      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          file: coverage/lcov.info
        continue-on-error: true

  build_check_android:
    name: Build Check (Android dev)
    runs-on: ubuntu-latest
    needs: analyze_and_test

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          cache: true
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - run: flutter pub get
      - run: flutter build apk --flavor dev -t lib/main_dev.dart --release
''';

  String _deployFlavor(String flavor, String branch) => '''
# Generated by flutter_cicd_wizard
# Deploy $flavor build on push to $branch

name: Deploy ${flavor[0].toUpperCase()}${flavor.substring(1)}

on:
  push:
    branches: [ $branch ]

jobs:
  deploy_android_$flavor:
    name: Android → Firebase ($flavor)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          cache: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Ruby (Fastlane)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Deploy via Fastlane
        env:
          FIREBASE_TOKEN: \${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_APP_ID_ANDROID_${flavor.toUpperCase()}: \${{ secrets.FIREBASE_APP_ID_ANDROID_${flavor.toUpperCase()} }}
        run: bundle exec fastlane android distribute_firebase flavor:$flavor

  deploy_ios_$flavor:
    name: iOS → Firebase ($flavor)
    runs-on: macos-latest
    needs: deploy_android_$flavor

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          cache: true

      - name: Setup Ruby (Fastlane)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Deploy via Fastlane
        env:
          FIREBASE_TOKEN: \${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_APP_ID_IOS_${flavor.toUpperCase()}: \${{ secrets.FIREBASE_APP_ID_IOS_${flavor.toUpperCase()} }}
          MATCH_GIT_URL: \${{ secrets.MATCH_GIT_URL }}
          MATCH_GIT_TOKEN: \${{ secrets.MATCH_GIT_TOKEN }}
          MATCH_PASSWORD: \${{ secrets.MATCH_PASSWORD }}
        run: bundle exec fastlane ios distribute_firebase flavor:$flavor
''';

  String _deployProd() => '''
# Generated by flutter_cicd_wizard
# Deploy PROD — triggers on push to main or version tag (v*)

name: Deploy Production

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  deploy_android_prod:
    name: Android → Play Store (prod)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          cache: true
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - run: flutter pub get

      - name: Bump version code
        run: bundle exec fastlane android bump_version

      - name: Deploy to Play Store
        env:
          PLAY_STORE_JSON_KEY: \${{ secrets.PLAY_STORE_JSON_KEY }}
        run: bundle exec fastlane android deploy_play_store

  deploy_ios_prod:
    name: iOS → TestFlight (prod)
    runs-on: macos-latest
    needs: deploy_android_prod

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          cache: true
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - run: flutter pub get

      - name: Deploy to TestFlight
        env:
          APP_STORE_CONNECT_KEY_PATH: \${{ secrets.APP_STORE_CONNECT_KEY_PATH }}
          MATCH_GIT_URL: \${{ secrets.MATCH_GIT_URL }}
          MATCH_GIT_TOKEN: \${{ secrets.MATCH_GIT_TOKEN }}
          MATCH_PASSWORD: \${{ secrets.MATCH_PASSWORD }}
        run: bundle exec fastlane ios deploy_testflight
''';

  String _codemagicNote() => '''
# Codemagic Alternative

If you prefer Codemagic over GitHub Actions, this tool generates
GitHub Actions by default. For Codemagic, run:

```
flutter_cicd_wizard --ci codemagic
```

(Coming in v1.1.0)
''';
}
